
---
- name: Download node exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract node exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes


- name: Start node exporter
  shell: |
    nohup /opt/node_exporter-1.6.0.linux-amd64/node_exporter \
    > /var/log/node_exporter.log 2>&1 &


---
