
---
- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus-2.45.0.linux-amd64/prometheus.yml

- name: Start Prometheus service
  shell: |
    nohup /opt/prometheus-2.45.0.linux-amd64/prometheus \
    --config.file=/opt/prometheus-2.45.0.linux-amd64/prometheus.yml \
    > /var/log/prometheus.log 2>&1 &


---
